services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dispatch
      POSTGRES_PASSWORD: dispatch
      POSTGRES_DB: dispatch
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dispatch']
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_port_connectivity']
      interval: 10s
      timeout: 5s
      retries: 5

  users:
    build:
      context: .
      dockerfile: services/users/Dockerfile
    environment:
      - PORT=4001
      - DATABASE_URL=postgresql://dispatch:dispatch@postgres:5432/dispatch?schema=users
      - JWT_SECRET=dev-secret
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '14001:4001'
    command: sh -c "pnpm -C services/users exec prisma migrate deploy && node services/users/dist/main.js"

  orders:
    build:
      context: .
      dockerfile: services/orders/Dockerfile
    environment:
      - PORT=4002
      - DATABASE_URL=postgresql://dispatch:dispatch@postgres:5432/dispatch?schema=orders
      - JWT_SECRET=dev-secret
      - NODE_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - '14002:4002'
    command: sh -c "pnpm -C services/orders exec prisma migrate deploy && node services/orders/dist/services/orders/src/main.js"

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    environment:
      - PORT=3000
      - USERS_URL=http://users:4001
      - ORDERS_URL=http://orders:4002
      - JWT_SECRET=dev-secret
      - NODE_ENV=development
    depends_on:
      users:
        condition: service_started
      orders:
        condition: service_started
    ports:
      - '3000:3000'

volumes:
  pgdata: {}
  redisdata: {}
